### ISSUE TITLE
How to solve as a person without seeing the solutions?

### ISSUE THREAD

**Issue by dpaleka** [protagolabs/odyssey-math#1]
I want to subsample a few of these problems to compare the reported model performance with human accuracy. The PDF seems to have solutions. Is it possible to provide a PDF or any sort of file without solutions, or with the solutions somehow hidden at the end?

**Comment by elricwan** [comment]
If you are looking for questions only pdf, you can download it directly from this link:
https://www.agiodyssey.org/#/MathContest
