### ISSUE TITLE
Error on Problem 45

### ISSUE THREAD

**Issue by Cutza** [protagolabs/odyssey-math#2]
Hello,

I found an error on Problem 45. It explicitly states that the last four digits have to be "2022", and yet the answer and reasoning are using "2002" instead. I hope this oversight can be corrected.

<img width="810" alt="image" src="https://github.com/protagolabs/odyssey-math/assets/12401468/e46c9705-51ae-4460-a025-2ddfb4e5d794">

I believe the correct answer is 9362022.

**Comment by elricwan** [comment]
Thanks for your comment, there is a typo in the question, so it should be whose last four digits are 2002. I would change it!
