### ISSUE TITLE
Your test are wrong!

### ISSUE THREAD

**Issue by withwsf** [protagolabs/odyssey-math#4]
In your prompt, you ask LLM to generate answer first then genrate reasoning.
In your setting, CoT does not work at all, all your result are not reliable

**Comment by elricwan** [comment]
This is the prompt we used:

SOLUTION = [
    {
        "role": "system",
        "content": """
            You are now assuming the role of a math professor. Your task is to assist the user by solving complex mathematical problems in a detailed and step-by-step manner.

            ## Task Requirements:
            1. **Detailed Problem Analysis**: Start by analyzing the given problem. Identify and articulate the key mathematical concepts and techniques needed to solve the problem.
            2. **Step-by-Step Solution**: Decompose the problem into manageable steps. Solve each step sequentially, ensuring logical progression and coherence in your approach.
            3. **Theoretical Justification**: For each step, provide a clear explanation of the mathematical theories or principles applied. Justify your choice of method and demonstrate how it applies to the specific problem at hand.
            4. **Calculation Verification**: After solving each step, verify your calculations. Explain any checks or balances you use to ensure the accuracy of your computations.
            5. **Error Checking and Assumptions**: State any assumptions made during the solution process. Discuss potential errors or alternative methods that could impact the solution.
            6. **Conclusive Summary**: Conclude with a summary of how the steps tie together and confirm the solution's validity.

            ## Expected Output Format:
            Present your final answer and the complete solution process in a JSON format. This should include:
                - A `float` value or a mathematical algebraic expression for the answer.
                - Detailed reasoning for each step of the solution.

            Your output should be formatted as a JSON object enclosed in Markdown code blocks tagged with 'json'. For example:
            
            ```json
            {{
                "answer": "<answer>",
                "reasoning": "<detailed solution process>"
            }}
            ```
            Ensure that all task requirements are meticulously followed in your response.
        """
    },
    {
        "role": "user",
        "content": "Here is the question: {question}."
    }
]

In the Requirements, we already stated the analysis, step by step, and more. The CoT is involved.
We are not saying our prompts would definitely give the best outcomes. If your prompt generate better performance score  with the same model. Please let us know so we can update the repo.

**Comment by withwsf** [comment]
？
